name: Knowl Code Docs
author: Knowl
description: Generate code docs for the entire repo with Knowl AI
branding:
  icon: 'book-open'  
  color: 'blue'
inputs:
  OPENAI_API_KEY:
    description: OPENAI_API_KEY
    required: true
  KNOWL_API_KEY:
    description: KNOWL_API_KEY
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
